name = "unihack-2026"
type = "javascript"
main = "index.ts"
compatibility_date = "2026-03-13"

[triggers]
crons = ["0 */2 * * *"]

[vars]
GEMINI_API_KEY = ""
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_API_TOKEN = ""
SUPABASE_SERVICE_ROLE_KEY = ""
SUPABASE_URL = ""
SUPABASE_PUBLISHABLE_KEY = ""

[observability]
[observability.logs]
enabled = true
invocation_logs = true
