name = "unihack-2026"
type = "javascript"
main = "index.ts"
compatibility_date = "2026-03-13"

[vars]
GEMINI_API_KEY = "api key here"
SUPABASE_SERVICE_ROLE_KEY = " Service role"
SUPABASE_URL = "https://wgyleywyxkbhbqldocif.supabase.co"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
